/* CRIANDO O BANCO DE DADOS */
CREATE DATABASE LOJAINFORMATICA

/* USANDO O BANCO DE DADOS */
USE LOJAINFORMATICA

/* CRIANDO AS TABELAS DO BANCO DE DADOS */

CREATE TABLE FUNCIONARIO(
COD_FUNC INT PRIMARY KEY IDENTITY,
NOME_FUNC VARCHAR(20)
)

CREATE TABLE PRODUTO(
COD_PROD INT PRIMARY KEY IDENTITY,
NOME_PROD VARCHAR(50),
QUANT_PROD INT
)

CREATE TABLE CLIENTE(
COD_CLIENTE INT PRIMARY KEY IDENTITY,
NOME_CLIENTE VARCHAR(50)
)

CREATE TABLE PEDIDO(
COD_PEDIDO INT PRIMARY KEY IDENTITY,
DESC_PEDIDO VARCHAR(100),
VALOR_PEDIDO FLOAT,
FK_COD_PROD INT,
FK_COD_CLIENTE INT,
FOREIGN KEY(FK_COD_PROD) REFERENCES PRODUTO(COD_PROD),
FOREIGN KEY(FK_COD_CLIENTE) REFERENCES CLIENTE (COD_CLIENTE)
)

CREATE TABLE VENDA(
COD_VENDA INT PRIMARY KEY IDENTITY,
FORMA_PAG VARCHAR(20),
FK_COD_PEDIDO INT,
FOREIGN KEY(FK_COD_PEDIDO) REFERENCES PEDIDO (COD_PEDIDO)
)

/* CONSULTANDO AS TABELAS DO BANCO DE DADOS */
SELECT * FROM FUNCIONARIO
SELECT * FROM CLIENTE
SELECT * FROM PRODUTO
SELECT * FROM PEDIDO
SELECT * FROM VENDA

/* CONSULTANDO COLUNAS ESPECIFICAS DAS TABELAS DO BANCO DE DADOS */

SELECT NOME_CLIENTE, DESC_PEDIDO
FROM CLIENTE, PEDIDO
WHERE CLIENTE.COD_CLIENTE = PEDIDO.COD_PEDIDO

/* ADICIONANDO CONTEÚDO NAS TABELAS DO BANCO DE DADOS */

/* FUNCIONARIO */
INSERT INTO FUNCIONARIO (NOME_FUNC)
VALUES ('Kaique'),
('Cidade'),
('Wellington')

/* CLIENTE */

INSERT INTO CLIENTE (NOME_CLIENTE, EMAIL)
VALUES ('Giovanna', 'giovaninha23@hotmail.com'),
('Beatriz', 'beatrizinha22@gmail.com'),
('Ramon', 'ramonzitcho95@outlook.com')

/* PRODUTO */

INSERT INTO PRODUTO (NOME_PROD, QUANT_PROD)
VALUES ('Monitor AOC 23 144hz', 5),
('Placa de Vídeo RTX 3070Ti 8GB EVGA', 2),
('Processador AMD Ryzen 5600x Zen3', 10)

/* PEDIDO */

INSERT INTO PEDIDO (DESC_PEDIDO, VALOR_PEDIDO, FK_COD_PROD, FK_COD_CLIENTE)
VALUES ('Processador AMD Ryzen 5600x', 2100.00, 3, 1)

INSERT INTO PEDIDO (DESC_PEDIDO, VALOR_PEDIDO, FK_COD_PROD, FK_COD_CLIENTE)
VALUES ('Placa de Vídeo RTX 3070Ti 8GB EVGA', 6500.00, 2, 3),  /* 2 */
('Monitor AOC 23 144hz', 1300.00, 1, 2) /* 3 */ 

/* VENDA */

INSERT INTO VENDA (FORMA_PAG, FK_COD_PEDIDO)
VALUES ('Dinheiro', 1)

INSERT INTO VENDA (FORMA_PAG, FK_COD_PEDIDO, DESC_VENDA)
VALUES ('Cartão de Crédito', 2, 'Placa de Vídeo RTX 3070Ti 8GB EVGA'),
('Débito', 3, 'Monitor AOC 23 144hz')

/* ALTERANDO INFORMAÇÕES NAS TABELAS DO BANCO DE DADOS */

/* CLIENTE */

ALTER TABLE CLIENTE
ADD CLIENTE_EMAIL VARCHAR(80)

ALTER TABLE CLIENTE
ADD EMAIL VARCHAR(80)

ALTER TABLE CLIENTE
DROP COLUMN CLIENTE_EMAIL

/* VENDA */

ALTER TABLE VENDA
ADD DESC_VENDA VARCHAR(80)


